version: "3.7"

services:
  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: yarn start
    volumes: 
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports: 
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  mariadb:
    image: "mariadb:${MARIADB_VERSION}"
    container_name: "mariadb-duckrace-dev"
    ports:
      - 3306:3306
    restart: 'always'
    volumes:
      - "/var/lib/mysql/data"
      - "/var/lib/mysql/logs"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
volumes:
  node_modules: